### ISSUE TITLE
devnet same address, nonce tx success

### ISSUE THREAD

**Issue by Lawliet-Chan** [reddio-com/reddio#136]

**Comment by haisenCx** [comment]
tx.nonce should be equal to state.nonce before a transaction executed, because state.nonce is actually obtained by calling the eth_getTransactionCount RPC method, which returns the total number of transactions from the 'from' address. The nonce of a new transaction should be equal to this value. For example, if the total number of transactions for a new address is 0, then the nonce of the new transaction should also be 0, not 1. The most direct proof of this is that there are definitely transactions with nonce 0 on the Ethereum network now.
